
USE [ageDB]
GO
/****** Object:  Table [dbo].[Flowchart118]    Script Date: 01/04/2019 7:05:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[StudentTable](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[IDNo] [varchar](50) NULL,
	[CoursesTaken] [varchar](300) NULL,

 CONSTRAINT [PK_StudentTable] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
