
USE [ageDB]

	INSERT INTO FlowchartTable115 (TermNo, Course,CourseTitle,Units, SoftReq, CoReq, HardReq) 
	VALUES
('1st Term','NSTP101','National Service Training Program General-Orientation',0,null,null,null),
('1st Term','PERSEF1','Personal Effectiveness 1',(2),null,null,null),
('1st Term','LASARE1','Lasallian Recollection 1',0,null,null,null),
('1st Term','FITWELL','Physical Fitness and Wellness',2,null,null,null),
('1st Term','ENGLCOM','Basic Communication and Study Skills',3,null,null,null),
('1st Term','ENGALG1','College Algebra for Engineering',3,null,null,null),
('1st Term','ENGTRIG','Plane and Spherical Trigonometry for Engineering',3,null,'ENGTRIG',null),
('1st Term','CHEMONE','General Chemistry 1',3,null,null,null),
('1st Term','LBYCH11','General Chemistry 1 Laboratory',1,null,'CHEMONE',null),
('1st Term','GRAPONE','Engineering Graphics 1',1,null,null,null),

('2nd Term','NSTP-R1/C1','National Service Training Program 1',(3),null,null,null),
('2nd Term','FTSPORT','Physical Fitness and Wellness in Individual/Dual Sport',2,'FITWELL',null,null),
('2nd Term','ENGLRES','Basic Research Skills/English for Specific Purposes',3,null,null,'ENGLCOM'),
('2nd Term','FILKOMU','Komunikasyon sa Filipinohiya',3,null,null,null),
('2nd Term','ANAGEOM','Analytic Geometry',2,null,null,'ENGALG1/ENGTRIG'),
('2nd Term','DIFFCAL','Differential Calculus',4,null,'ANAGEOM','ENGALG1/ENGTRIG'),
('2nd Term','SOLIMEN','Solid Mensuration',2,null,'ANAGEOM',null),
('2nd Term','SOCTEC1','Science, Technology, and Society 1',3,null,null,null),
('2nd Term','LBYMEEA','Engineering Graphics 2 (CAD)',1,null,null,'GRAPONE'),

('3rd Term','SAS1000','Students Affairs Services 1000',0,null,null,null),
('3rd Term','NSTP-R2/C2','National Service Training Program 2',(3),null,null,'NSTP-R1/C1'),
('3rd Term','ENGPHY1','Engineering Physics 1',3,'DIFFCAL',null,null),
('3rd Term','LBYPH11','Engineering Physics 1 Laboratory',1,null,'ENGPHY1',null),
('3rd Term','FTDANCE','Physical Fitness and Wellness in Dance',2,'FITWELL',null,null),
('3rd Term','SPEECOM','Oral Communication/Advanced Speech Class',3,null,null,'ENGLCOM'),
('3rd Term','FILDLAR','Pagbasa at Pagsulat sa lbat Ibang Disiplina',3,null,null,'FILKOMU'),
('3rd Term','INTECAL','Integral Calculus',4,null,null,'DIFFCAL'),
('3rd Term','ENGALG2','Advanced Algebra for Engineering',2,null,null,'ENGALG1'),
('3rd Term','MENGIOR','Mechanical Engineering Orientation',1,null,null,null),
('3rd Term','LBYME11','Mechanical Processes 1',1,null,null,null),

('4th Term','LBYEC71','Computer Fundamentals & Programming 1',1,'ENGALG1',null,null),
('4th Term','THERMO1','Basic Mechanical Engineering Thermodynamics',3,'INTECAL',null,null),
('4th Term','ENGIANA','Differential Equations',3,null,null,'INTECAL'),
('4th Term','ENGPHY2','Engineering Physics 2',3,null,null,'ENGPHY1'),
('4th Term','LBYPH12','Engineering Physics 2 Laboratory',1,null,'ENGPHY2','LBYPH11'),
('4th Term','SOCTEC2','Science, Technology, and Society 2',3,null,null,'SOCTEC1'),
('4th Term','LBYME12','Mechanical Processes 2',1,null,null,'LBYME11'),
('4th Term','TREDONE','Humanity’s Search for Life',3,null,null,null),
('4th Term','ENGSAFE','Safety Management for Engineering',1,null,null,null),

('5th Term','HUMALIT','Introduction to Literature',3,null,null,'ENGLRES'),
('5th Term','THERMO2','Advanced Mechanical Engineering Thermodynamics',3,null,null,'THERMO1'),
('5th Term','NUMERIC','Numerical Methods',1,null,'ADMEMAT',null),
('5th Term','LBYMEEN','Numerical Methods Laboratory',1,null,'NUMERIC',null),
('5th Term','STATICS','Statics of Rigid Bodies',3,'INTECAL',null,'ENGPHY1'),
('5th Term','ADMEMAT','Advanced Engineering Mathematics for ME',2,null,null,'ENGIANA'),
('5th Term','INTFILO','Introductory Philosophy',3,null,null,null),
('5th Term','LBYME13','Mechanical Processes 3',1,null,null,'LBYME12'),
('5th Term','LBYME15','Mechanical Engineering Laboratory 1',1,'THERMO1',null,null),
('5th Term','LBYMEEB','Mechanical Engineering CADD 1',1,null,null,'LBYMEEA'),

('6th Term','FTTEAMS','Physical Fitness and Wellness in Team Sports',2,'FITWELL',null,null),
('6th Term','TREDTWO','The Filipino Christian in a Changing World',3,null,null,'TREDONE'),
('6th Term','MEEHEAT','Heat Transfer for ME',2,'THERMO2',null,null),
('6th Term','FLUIDME','Fluid Mechanics',3,'THERMO1',null,'STATICS/ADMEMAT'),
('6th Term','MENGECO','Engineering Economy for ME',3,'DIFFCAL',null,null),
('6th Term','DYNAMIC','Dynamics of Rigid Bodies',2,null,null,'STATICS'),
('6th Term','ELENPRI','Electrical Engineering Principles',3,null,null,'ENGPHY2'),
('6th Term','LBYEC74','Electrical Engineering Principles Laboratory',1,null,'ELENPRI','LBYPH12'),
('6th Term','LBYEC72','Computer Fundamentals & Programming 2',1,null,null,'LBYEC71'),
('6th Term','LASARE2','Lasallian Recollection 2',0,null,null,'LASARE1'),

('7th Term','KINMAC1','Kinematics and Machine Elements 1',2,null,null,'DYNAMIC'),
('7th Term','LBYMEEK','Machine Elements 1 Laboratory',1,null,'KINMAC1',null),
('7th Term','REFRENG','Refrigeration Engineering',3,null,null,'MEEHEAT'),
('7th Term','MEVIBEN','Vibration Engineering for ME',2,null,null,'DYNAMIC/ENGIANA'),
('7th Term','COMBUST','Combustion Engineering',2,null,null,'THERMO2'),
('7th Term','MEDEFOR','Mechanics of Deformable Bodies',3,'DYNAMIC',null,null),
('7th Term','MACHENG','DC and AC Machinery',2,null,null,'ELENPRI'),
('7th Term','LBYEC75','DC and AC Machinery Laboratory',1,null,'MACHENG','LBYEC74'),
('7th Term','LBYMEEC','Mechanical Engineering CADD 2',1,null,null,'LBYMEEB'),
('7th Term','LBYME16','Mechanical Engineering Laboratory 2',1,'FLUIDME',null,'LBYME15'),

('8th Term','KINMAC2','Kinematics and Machine Elements 2',2,null,null,'KINMAC1'),
('8th Term','LBYMEEL','Machine Elements 2 Laboratory',1,null,'KINMAC1','LBYMEEK'),
('8th Term','FLUIMAC','Fluid Machinery',3,null,null,'FLUIDME'),
('8th Term','MEREMEE','Methods of Research for ME',1,null,null,'ENGLRES'),
('8th Term','MEEMATS','Materials Science and Engineering',3,'MEDEFOR',null,'CHEMONE'),
('8th Term','LBYME19','Materials Science and Engineering Laboratory',1,null,'MEEMATS',null),
('8th Term','AIRCOVE','Air Conditioning and Ventilation Systems',2,null,null,'REFRENG'),
('8th Term','LBYMEEM','Air Conditioning and Ventilation Systems Laboratory',1,null,'AIRCOVE',null),
('8th Term','ELTROME','Basic Electronics for ME',3,null,null,'ELENPRI'),
('8th Term','LBYEC76','Basic Electronics Laboratory for ME',1,null,'ELTROME','LBYEC74'),

('9th Term','TREDTRI','The Christian and the Word',3,null,null,'TREDTWO'),
('9th Term','GREATWK','The Great Works',3,null,null,null),
('9th Term','ENGSTAT','Probability and Statistics for Engineering',3,'INTECAL',null,null),
('9th Term','MADEONE','Machine Design 1',3,'KINMAC2',null,'MEDEFOR'),
('9th Term','DIELECT','Digital Electronics for ME',3,null,null,'ELTROME'),
('9th Term','LBYEC77','Digital Electronics Laboratory for ME',1,null,'DIELECT','LBYEC76'),
('9th Term','THSMEEA','Mechanical Engineering Project Study 1',1,'MENGECO/ELTROME/KINMAC2/FLUIDME',null,'MEREMEE'),
('9th Term','LBYME14','Fundamentals of CNC Machines',1,null,null,'LBYME13'),
('9th Term','PERSEF2','Personal Effectiveness 2',(2),null,null,'PERSEF1'),

('10th Term','MEESAFE','Mechanical Engineering Safety',2,null,null,'ENGSAFE'),
('10th Term','ENVIRON','Environmental Engineering',2,'CHEMONE',null,null),
('10th Term','INPLANT','Industrial Plant Design',3,null,null,'FLUIMAC/AIRCOVE'),
('10th Term','MADETWO','Machine Design 2',3,null,null,'MADEONE'),
('10th Term','MELECT1','Mechanical Engineering Elective 1',2,null,null,null),
('10th Term','LBYME17','Mechanical Engineering Laboratory 3',1,'FLUIMAC',null,'LBYME16'),
('10th Term','MEECONT','Controls Engineering for ME',3,'DIELECT/MEVIBEN',null,null),
('10th Term','LBYME21','Controls Engineering Laboratory for ME',1,null,'MEECONT',null),
('10th Term','THSMEEB','Mechanical Engineering Project Study 2',1,null,null,'THSMEEA'),

('11th Term','KASPIL1','Buhay, mga Sinulat at Nagawa ni Dr. Jose Rizal',3,null,null,null),
('11th Term','HUMAART','Introduction to Art',3,null,null,'ENGLRES'),
('11th Term','POPLADE','Power Plant Engineering',5,null,null,'COMBUST'),
('11th Term','MANAGEN','Engineering Management',3,null,null,null),
('11th Term','MECATRO','Mechatronics',2,null,null,'MEECONT/DIELECT/MACHENG'),
('11th Term','LBYME22','Mechatronics Laboratory',1,'LBYEC75/LBYME21','MECATRO',null),
('11th Term','LBYMEEP','Computer Methods for ME',1,null,null,'MADEONE/FLUIDME'),

('12th Term','IPERSEF','Integrating Course for Personal Effectiveness',0,null,null,'PERSEF2'),
('12th Term','LASARE3','Lasallian Recollection 3',0,null,null,'LASARE2'),
('12th Term','KASPIL2','Kasaysayan ng Pilipinas',3,null,null,'KASPIL1'),
('12th Term','TREDFOR','The Christian Vocation of Life',3,null,null,'TREDTRI'),
('12th Term','INPROME','Industrial Processes for ME',2,'INPLANT',null,null),
('12th Term','METHICO','ME Laws, Ethics, Codes and Standards',3,null,null,null),
('12th Term','MELECT2','Mechanical Engineering Elective 2',2,null,null,null),
('12th Term','LBYME18','Mechanical Engineering Laboratory 4',1,'POPLADE',null,'LBYME17'),
('12th Term','THSMEEC','Mechanical Engineering Project Study 3',1,null,null,'THSMEEB'),

('13th Term','PRCMEE1','Mechanical Engineering Practicum',2,null,null,'PERSEF2')
