USE [ageDB]
 t Term
 INSERT INTO FlowchartTable118 (TermNo, Course,CourseTitle,Units, SoftReq, CoReq, HardReq)
 VALUES

('Term 1','NSTP101','National Service Training Program – General Orientation',0,null,null,null),
('Term 1','FNDMATH','Foundation Course in Mathematics',5,null,null,null),
('Term 1','BASCHEM','Basic Chemistry',3,null,null,null),
('Term 1','BASPHYS','Basic Physics',3,null,null,null),
('Term 1','FNDSTAT','Foundation Course in Statistics',3,null,null,null),
('Term 1','MENGIOR','Mechanical Engineering Orientation',1,null,null,null),
('Term 1','LBYME1A','Engineering Drawing',1,null,null,null),
 
('Term 2','NSTPCW1','National Service Training Program 1',3,null,null,'NSTP101'),
('Term 2','GEMATMW','Mathematics in the Modern World',3,null,null,null),
('Term 2','GEFTWEL','Physical Fitness and Wellness',2,null,null,null),
('Term 2','CALENG1','Differential Calculus',3,null,null,'FNDMATH'),
('Term 2','ENGCHEM','Chemistry for Engineers',3,null,null,'BASCHEM'),
('Term 2','LBYCH1A','Chemistry for Engineers Laboratory',1,null,'ENGCHEM',null),
('Term 2','LBYME1B','Engineering Computer-Aided Drafting',1,null,null,'LBYME1A'),
('Term 2','LBYME1D','Mechanical Processes 1',1,null,null,null),
('Term 2','EMAMECH','Engineering Management for ME',2,null,'CALENG1',null),
('Term 2','LBYEC2A','Computer Fundamentals and Programming',1,null,null,null),
 
('Term 3','NSTPCW2','National Service Training Program 2',3,null,null,'NSTPCW1'),
('Term 3','SAS1000','Student Affairs Services 1000',0,null,null,null),
('Term 3','GEFILI1','Introduksyon sa Filipinohiya',3,null,null,null),
('Term 3','GEDANCE','Physical Fitness and Wellness in Dance',2,null,null,null),
('Term 3','LCLSONE','Lasallian Studies 1',1,null,null,null),
('Term 3','LASARE1','Lasallian Recollection 1',0,null,null,null),
('Term 3','CALENG2','Integral Calculus',3,null,null,'CALENG1'),
('Term 3','ENGPHYS','Physics for Engineers',3,'CALENG1',null,'BASPHYS'),
('Term 3','LBYPH1A','Physics for Engineers Laboratory',1,null,'ENGPHYS',null),
('Term 3','GEUSELF','Understanding the Self',3,null,null,null),
('Term 3','MECECON','Engineering Economics for ME',3,'CALENG1',null,null),
('Term 3','LBYME1E','Mechanical Processes 2',1,'LBYME1D',null,null),
 
('Term 4','GEFILI2','Mga Usaping Pang-wika sa iba’t-ibang Larangan',3,null,null,null),
('Term 4','GESPORT','Physical Fitness and Wellness in Individual Sports',2,null,null,null),
('Term 4','CALENG3','Differential Equations',3,null,null,'CALENG2'),
('Term 4','ENGMEC1','Statics of Rigid Bodies',3,'CALENG2',null,'ENGPHYS'),
('Term 4','LBYME2A','Computer Aided Design for ME',1,null,null,'LBYME1B'),
('Term 4','METHER1','Basic Mechanical Engineering Thermodynamics',3,'CALENG1',null,'ENGPHYS'),
('Term 4','MEBASEE','Basic Electrical Engineering for ME',2,null,null,'ENGPHYS'),
('Term 4','LBYEC2K','Basic Electrical Engineering for ME Laboratory',1,null,null,'MEBASEE'),
('Term 4','LBYME2B','Mechanical Processes 3',1,null,null,'LBYME1E'),
 
('Term 5','GEPCOMM','Purposive Communications',3,null,null,null),
('Term 5','GETEAMS','Physical Fitness and Wellness in Team Sports',2,null,null,null),
('Term 5','ENGMEC2','Dynamics of Rigid Bodies',2,'ENGMEC1',null,null),
('Term 5','METHER2','Advanced Mechanical Engineering Thermodynamics',3,null,null,'METHER1'),
('Term 5','MECHFLU','Fluid Mechanics',3,null,null,'METHER1'),
('Term 5','MEMACHI','DC and AC Machinery',2,null,null,'MEBASEE'),
('Term 5','LBYEC2L','DC and AC Machinery Laboratory',1,null,'MEMACHI','LBYEC2K'),
('Term 5','MEADMAT','Advanced Mathematics for ME',3,null,null,'CALENG3'),
 
('Term 6','DATAENG','Engineering Data Analysis',3,'CALENG2',null,'FNDSTAT'),
('Term 6','LCFAITH','Faith Worth Living',3,null,null,null),
('Term 6','LCLSTWO','Lasallian Studies 2',1,null,null,'LCLSONE'),
('Term 6','LASARE2','Lasallian Recollection 2',0,null,null,null),
('Term 6','MEHETRA','Heat Transfer',2,null,null,'METHER1'),
('Term 6','ENGMEC3','Mechanics of Deformable Bodies',3,null,null,'ENGMEC1'),
('Term 6','MACHELE','Machine Elements',2,null,null,'ENGMEC2'),
('Term 6','LBYME2D','Machine Elements Laboratory',1,null,'MACHELE',null),
('Term 6','MECFLUM','Fluid Machineries',3,null,null,'MECHFLU'),
('Term 6','LBYME2C','Mechanical Engineering Laboratory 1',1,'METHER1',null,null),
 
('Term 7','GEARTAP','Art Appreciation',3,null,null,null),
('Term 7','GEETHIC','Ethics',3,null,null,null),
('Term 7','REFSYST','Refrigeration Systems',3,null,null,'MEHETRA'),
('Term 7','MECMATS','Materials Science for ME',2,'ENGMEC3',null,'ENGCHEM'),
('Term 7','LBYME3A','Materials Science for ME Laboratory',1,null,'MECMATS',null),
('Term 7','ELECME1','Basic Electronics for ME',2,null,null,'MEBASEE'),
('Term 7','LBYEC3P','Basic Electronics for ME Laboratory',1,null,'ELECME1',null),
('Term 7','LBYME3B','Machine Elements Laboratory 2',1,'MEHETRA',null,'LBYME2C'),
('Term 7','LBYEC3A','Intelligent Engineering Systems',1,'DATAENG',null,'LBYEC2A'),
('Term 7','VIBEENG','Vibration Engineering',2,null,null,'CALENG3'),
 
('Term 8','GERIZAL','Life and Works of Rizal',3,null,null,null),
('Term 8','GESTSOC','Science, Technology and Society',3,null,null,null),
('Term 8','AIRVENT','Air-Conditioning and Ventilation Systems',3,null,null,'REFSYST'),
('Term 8','MERESME','Methods of Research for ME',1,'DATAENG',null,null),
('Term 8','ELECME2','Digital Electronics for ME',2,null,null,'ELECME1'),
('Term 8','LBYEC3Q','Digital Electronics for ME Laboratory',1,null,'ELECME2','LBYECP3P'),
('Term 8','MAINPRO','Manufacturing and Industrial Processes',1,null,null,null),
('Term 8','MECOMBE','Combustion Engineering',2,null,null,'METHER2'),
('Term 8','LBYME3C','Computer Applications for ME',1,null,null,'LBYEC2A'),
('Term 8','LBYME3D','CNC Machines',1,null,null,'LBYME2B'),
 
('Term 9','GELITPH','Literatures of the Philippines',3,null,null,null),
('Term 9','LCASEAN','The Filipino and the ASEAN',3,null,null,null),
('Term 9','LCLSTRI','Lasallian Studies 3',1,null,null,'LCLSTWO'),
('Term 9','LASARE3','Lasallian Recollection 3',0,null,null,null),
('Term 9','MADESN1','Machine Design',3,null,null,'MACHELE/ENGMEC3'),
('Term 9','THSMEC1','Mechanical Engineering Project Study 1',1,null,null,'MERESME'),
('Term 9','LBYME3E','Mechanical Engineering Laboratory 3',1,'MECFLUM',null,'LBYME3B'),
('Term 9','CONTEME','Controls Engineering for ME',2,'VIBEENG/MEBASEE',null,null),
('Term 9','LBYME3F','Controls Engineering for ME Laboratory',1,null,'CONTEME',null),
('Term 9','INDULPA','Industrial Plant Engineering',4,null,null,'AIRVENT/MAINPRO'),
 
('Term 10','LCENWRD','Encountering the Word in the World',3,null,null,null),
('Term 10','MADESN2','Machine Design 2',3,null,null,'MADESN1'),
('Term 10','MECAPST','Mechanical Engineering Capstone Project',1,null,null,'THSMEC1'),
('Term 10','LBYME4A','Mechanical Engineering Laboratory 4',1,'AIRVENT',null,'LBYME3E'),
('Term 10','MECENGI','Mechatronics Engineering',2,null,null,'ELECME/CONTEME'),
('Term 10','LBYME4B','Mechatronics Engineering Laboratory',1,null,null,'LBYME3F'),
('Term 10','POPLANT','Power Plant Engineering',4,null,null,'MECOMBE'),
('Term 10','MEETHIC','MELaws, Ethics, Codes, and Standards',2,null,null,'ETHICS'),
('Term 10','MELECT1','Mechanical Engineering Elective 1',2,null,null,null),
 
('Term 11','GERPHIS','Reading in the Philippine History',3,null,null,null),
('Term 11','GEWORLD','The Contemporary World',3,null,null,null),
('Term 11','THSMEC2','Mechanical Engineering Project Study 2',1,null,null,'THSMEC1'),
('Term 11','ENGTREP','Technopreneurship',2,null,null,null),
('Term 11','MELECT2','Mechanical Engineering Elective 2',2,null,null,null),
('Term 11','LBYME4C','Mechanical Engineering Laboratory 5',1,'POPLANT',null,'LBYME4A'),
('Term 11','BOSHEAL','Basic Occupational Safety and Health',3,null,null,null),
('Term 11','INTMECH','Integration Course for ME',1,null,null,'INDUPLA/POPLANT/MADESN2'),
 
('Term 12','PRCGEME','Mechanical Engineering Practicum',3,null,null,'ALL COURSES')
