USE [ageDB]
 
 INSERT INTO FlowchartTable118 (TermNo, Course,CourseTitle,Units, SoftReq, CoReq, HardReq)
 VALUES

('1st Term','NSTP101','National Service Training Program – General Orientation',0,null,null,null),
('1st Term','FNDMATH','Foundation Course in Mathematics',5,null,null,null),
('1st Term','BASCHEM','Basic Chemistry',3,null,null,null),
('1st Term','BASPHYS','Basic Physics',3,null,null,null),
('1st Term','FNDSTAT','Foundation Course in Statistics',3,null,null,null),
('1st Term','MENGIOR','Mechanical Engineering Orientation',1,null,null,null),
('1st Term','LBYME1A','Engineering Drawing',1,null,null,null),
 
('2nd Term','NSTPCW1','National Service Training Program 1',3,null,null,'NSTP101'),
('2nd Term','GEMATMW','Mathematics in the Modern World',3,null,null,null),
('2nd Term','GEFTWEL','Physical Fitness and Wellness',2,null,null,null),
('2nd Term','CALENG1','Differential Calculus',3,null,null,'FNDMATH'),
('2nd Term','ENGCHEM','Chemistry for Engineers',3,null,null,'BASCHEM'),
('2nd Term','LBYCH1A','Chemistry for Engineers Laboratory',1,null,'ENGCHEM',null),
('2nd Term','LBYME1B','Engineering Computer-Aided Drafting',1,null,null,'LBYME1A'),
('2nd Term','LBYME1D','Mechanical Processes 1',1,null,null,null),
('2nd Term','EMAMECH','Engineering Management for ME',2,null,'CALENG1',null),
('2nd Term','LBYEC2A','Computer Fundamentals and Programming',1,null,null,null),
 
('3rd Term','NSTPCW2','National Service Training Program 2',3,null,null,'NSTPCW1'),
('3rd Term','SAS1000','Student Affairs Services 1000',0,null,null,null),
('3rd Term','GEFILI1','Introduksyon sa Filipinohiya',3,null,null,null),
('3rd Term','GEDANCE','Physical Fitness and Wellness in Dance',2,null,null,null),
('3rd Term','LCLSONE','Lasallian Studies 1',1,null,null,null),
('3rd Term','LASARE1','Lasallian Recollection 1',0,null,null,null),
('3rd Term','CALENG2','Integral Calculus',3,null,null,'CALENG1'),
('3rd Term','ENGPHYS','Physics for Engineers',3,'CALENG1',null,'BASPHYS'),
('3rd Term','LBYPH1A','Physics for Engineers Laboratory',1,null,'ENGPHYS',null),
('3rd Term','GEUSELF','Understanding the Self',3,null,null,null),
('3rd Term','MECECON','Engineering Economics for ME',3,'CALENG1',null,null),
('3rd Term','LBYME1E','Mechanical Processes 2',1,'LBYME1D',null,null),
 
('4th Term','GEFILI2','Mga Usaping Pang-wika sa iba’t-ibang Larangan',3,null,null,null),
('4th Term','GESPORT','Physical Fitness and Wellness in Individual Sports',2,null,null,null),
('4th Term','CALENG3','Differential Equations',3,null,null,'CALENG2'),
('4th Term','ENGMEC1','Statics of Rigid Bodies',3,'CALENG2',null,'ENGPHYS'),
('4th Term','LBYME2A','Computer Aided Design for ME',1,null,null,'LBYME1B'),
('4th Term','METHER1','Basic Mechanical Engineering Thermodynamics',3,'CALENG1',null,'ENGPHYS'),
('4th Term','MEBASEE','Basic Electrical Engineering for ME',2,null,null,'ENGPHYS'),
('4th Term','LBYEC2K','Basic Electrical Engineering for ME Laboratory',1,null,null,'MEBASEE'),
('4th Term','LBYME2B','Mechanical Processes 3',1,null,null,'LBYME1E'),
 
('5th Term','GEPCOMM','Purposive Communications',3,null,null,null),
('5th Term','GETEAMS','Physical Fitness and Wellness in Team Sports',2,null,null,null),
('5th Term','ENGMEC2','Dynamics of Rigid Bodies',2,'ENGMEC1',null,null),
('5th Term','METHER2','Advanced Mechanical Engineering Thermodynamics',3,null,null,'METHER1'),
('5th Term','MECHFLU','Fluid Mechanics',3,null,null,'METHER1'),
('5th Term','MEMACHI','DC and AC Machinery',2,null,null,'MEBASEE'),
('5th Term','LBYEC2L','DC and AC Machinery Laboratory',1,null,'MEMACHI','LBYEC2K'),
('5th Term','MEADMAT','Advanced Mathematics for ME',3,null,null,'CALENG3'),
 
('6th Term','DATAENG','Engineering Data Analysis',3,'CALENG2',null,'FNDSTAT'),
('6th Term','LCFAITH','Faith Worth Living',3,null,null,null),
('6th Term','LCLSTWO','Lasallian Studies 2',1,null,null,'LCLSONE'),
('6th Term','LASARE2','Lasallian Recollection 2',0,null,null,null),
('6th Term','MEHETRA','Heat Transfer',2,null,null,'METHER1'),
('6th Term','ENGMEC3','Mechanics of Deformable Bodies',3,null,null,'ENGMEC1'),
('6th Term','MACHELE','Machine Elements',2,null,null,'ENGMEC2'),
('6th Term','LBYME2D','Machine Elements Laboratory',1,null,'MACHELE',null),
('6th Term','MECFLUM','Fluid Machineries',3,null,null,'MECHFLU'),
('6th Term','LBYME2C','Mechanical Engineering Laboratory 1',1,'METHER1',null,null),
 
('7th Term','GEARTAP','Art Appreciation',3,null,null,null),
('7th Term','GEETHIC','Ethics',3,null,null,null),
('7th Term','REFSYST','Refrigeration Systems',3,null,null,'MEHETRA'),
('7th Term','MECMATS','Materials Science for ME',2,'ENGMEC3',null,'ENGCHEM'),
('7th Term','LBYME3A','Materials Science for ME Laboratory',1,null,'MECMATS',null),
('7th Term','ELECME1','Basic Electronics for ME',2,null,null,'MEBASEE'),
('7th Term','LBYEC3P','Basic Electronics for ME Laboratory',1,null,'ELECME1',null),
('7th Term','LBYME3B','Machine Elements Laboratory 2',1,'MEHETRA',null,'LBYME2C'),
('7th Term','LBYEC3A','Intelligent Engineering Systems',1,'DATAENG',null,'LBYEC2A'),
('7th Term','VIBEENG','Vibration Engineering',2,null,null,'CALENG3'),
 
('8th Term','GERIZAL','Life and Works of Rizal',3,null,null,null),
('8th Term','GESTSOC','Science, Technology and Society',3,null,null,null),
('8th Term','AIRVENT','Air-Conditioning and Ventilation Systems',3,null,null,'REFSYST'),
('8th Term','MERESME','Methods of Research for ME',1,'DATAENG',null,null),
('8th Term','ELECME2','Digital Electronics for ME',2,null,null,'ELECME1'),
('8th Term','LBYEC3Q','Digital Electronics for ME Laboratory',1,null,'ELECME2','LBYECP3P'),
('8th Term','MAINPRO','Manufacturing and Industrial Processes',1,null,null,null),
('8th Term','MECOMBE','Combustion Engineering',2,null,null,'METHER2'),
('8th Term','LBYME3C','Computer Applications for ME',1,null,null,'LBYEC2A'),
('8th Term','LBYME3D','CNC Machines',1,null,null,'LBYME2B'),
 
('9th Term','GELITPH','Literatures of the Philippines',3,null,null,null),
('9th Term','LCASEAN','The Filipino and the ASEAN',3,null,null,null),
('9th Term','LCLSTRI','Lasallian Studies 3',1,null,null,'LCLSTWO'),
('9th Term','LASARE3','Lasallian Recollection 3',0,null,null,null),
('9th Term','MADESN1','Machine Design',3,null,null,'MACHELE/ENGMEC3'),
('9th Term','THSMEC1','Mechanical Engineering Project Study 1',1,null,null,'MERESME'),
('9th Term','LBYME3E','Mechanical Engineering Laboratory 3',1,'MECFLUM',null,'LBYME3B'),
('9th Term','CONTEME','Controls Engineering for ME',2,'VIBEENG/MEBASEE',null,null),
('9th Term','LBYME3F','Controls Engineering for ME Laboratory',1,null,'CONTEME',null),
('9th Term','INDULPA','Industrial Plant Engineering',4,null,null,'AIRVENT/MAINPRO'),
 
('10th Term','LCENWRD','Encountering the Word in the World',3,null,null,null),
('10th Term','MADESN2','Machine Design 2',3,null,null,'MADESN1'),
('10th Term','MECAPST','Mechanical Engineering Capstone Project',1,null,null,'THSMEC1'),
('10th Term','LBYME4A','Mechanical Engineering Laboratory 4',1,'AIRVENT',null,'LBYME3E'),
('10th Term','MECENGI','Mechatronics Engineering',2,null,null,'ELECME/CONTEME'),
('10th Term','LBYME4B','Mechatronics Engineering Laboratory',1,null,null,'LBYME3F'),
('10th Term','POPLANT','Power Plant Engineering',4,null,null,'MECOMBE'),
('10th Term','MEETHIC','MELaws, Ethics, Codes, and Standards',2,null,null,'ETHICS'),
('10th Term','MELECT1','Mechanical Engineering Elective 1',2,null,null,null),
 
('11th Term','GERPHIS','Reading in the Philippine History',3,null,null,null),
('11th Term','GEWORLD','The Contemporary World',3,null,null,null),
('11th Term','THSMEC2','Mechanical Engineering Project Study 2',1,null,null,'THSMEC1'),
('11th Term','ENGTREP','Technopreneurship',2,null,null,null),
('11th Term','MELECT2','Mechanical Engineering Elective 2',2,null,null,null),
('11th Term','LBYME4C','Mechanical Engineering Laboratory 5',1,'POPLANT',null,'LBYME4A'),
('11th Term','BOSHEAL','Basic Occupational Safety and Health',3,null,null,null),
('11th Term','INTMECH','Integration Course for ME',1,null,null,'INDUPLA/POPLANT/MADESN2'),
 
('12th Term','PRCGEME','Mechanical Engineering Practicum',3,null,null,'ALL COURSES')
